apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spring-petclinic
  name: spring-petclinic
  namespace: spring-petclinic
spec:
  selector:
    matchLabels:
      app: spring-petclinic
  template:
    metadata:
      labels:
        app: spring-petclinic
    spec:
      containers:
      - image: ghcr.io/kreiger/spring-petclinic:latest
        imagePullPolicy: Always
        name: spring-petclinic
        ports:
          - containerPort: 8080
